version: 2
jobs:
   build:
     working_directory: ~/dissertation
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: make
       - run: make oopsla
       - store_artifacts:
           path: ~/dissertation/thesis.pdf
           destination: thesis-draft.pdf
       - store_artifacts:
           path: ~/dissertation/oopsla19.pdf
           destination: oopsla19-submission.pdf
